### ISSUE TITLE
Erethic Question

### ISSUE THREAD

**Issue by magomimmo** [seancorfield/boot-expectations#5]
Hi @seancorfield, very nice stuff. That said I have an erethic question for you too:

Anyone having to do with testing in clj/cljs, even the `clojure.test` namespace, by default, takes into account all namespaces:

```clj
(core/input-dirs fs))
```

I never understood why? By default, I would filter all the namespaces starting with project main segment. Generally speaking, I want to test my own namespaces, not the ones from the others. I would assume that they already have their tests. Am I so wrong about it?

**Comment by seancorfield** [comment]
Two things:

* `input-dirs` only seems to list directories in your own project (I may be wrong -- and maybe `user-dirs` would be a better choice here -- but when I was testing this task, I only saw my own project's namespaces derived from all the input directories),
* Artifacts generally only ship with source files, not test files, so even if you examined everything on the classpath, you'd normally only see tests in your own project.

Hope that helps?

p.s. I had to go lookup "erethic" so thank you for teaching me a new word!

**Comment by seancorfield** [comment]
A deeper reading of `user-dirs` vs `input-dirs` indicates that the former represents just the original source, resource, and asset directories of the project, whereas the latter represents the set of directories that are inputs to the current task. I'm happy with the latter since it would allow an earlier task in the pipeline to preprocess the project files to generate tests that could then be run by the expectations task.

**Comment by magomimmo** [comment]
Thanks for your answer Sean. I have to admit that I do not use expectations because it's not portable on CLJS. But I now discovered that this lib has been created by @jaycfields, which means I'm not the only *heretic* (I learned a new word as well because of my typo) about `clojure.test` lib which has a  `run-all-tests` on all namespaces of the project:

http://blog.jayfields.com/2010/08/clojuretest-introduction.html

Probably your *beautiful* `boot-expectations` lib does not incur in the same problem that `boot-test` and `boot-cljs-test` generate by using `input-dirs` because it has been implemented with that *heretic* approach in mind. 

See [here](https://github.com/magomimmo/modern-cljs/blob/master/doc/second-edition/tutorial-16.md#test-namespaces) what could happen by using a vanilla `input-dirs` without filtering it. 

thanks again for your very appreciated work.

**Comment by jaycfields** [comment]
There was a fair bit of work to add cljs support, but I believe @imikushin added everything necessary and at least @ptaoussanis was using it (last I heard).

**Comment by magomimmo** [comment]
thanks for the link!

**Comment by ptaoussanis** [comment]
Just a heads-up that I was never able to get the Expectations ClojureScript support working properly. Might well be possible though, didn't spend too much time trying. Good luck! :-)

**Comment by magomimmo** [comment]
@ptaoussanis thanks!
